/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Mantenimientos;

import Clases.cConexion;
import org.jvnet.substance.SubstanceLookAndFeel;
import Procesos.busqueda;
import javax.swing.JOptionPane;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Manuel
 */
public class creacionempleado extends javax.swing.JFrame {

    /**
     * Creates new form creacionempleado
     */
    public creacionempleado() {
	initComponents();
		mostrardatos();
    }
void mostrardatos(){
    
	DefaultTableModel   modelo = new DefaultTableModel ();
	modelo.addColumn("Codigo");
	modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
	modelo.addColumn("Estado Civil");
        modelo.addColumn("Fecha de Nacimiento");
	modelo.addColumn("Telefono");
        modelo.addColumn("Correo");
	modelo.addColumn("Dirección");
        modelo.addColumn("Municipio");
	modelo.addColumn("Departamento");
        modelo.addColumn("DUI");
	modelo.addColumn("NIT");
        modelo.addColumn("ISSS");
        modelo.addColumn("AFP");
        modelo.addColumn("NUP");
        modelo.addColumn("Fecha de ingreso");       
        modelo.addColumn("Empresa");
        modelo.addColumn("Nivel");
        modelo.addColumn("Cargo");
        modelo.addColumn("Sueldo");

	tabla.setModel(modelo);
	String []datos = new String [18];
	try{
		Statement st= miConexion.createStatement();
		ResultSet rs = st.executeQuery("SELECT * FROM empleado");
		while (rs.next()){
		datos [0]=rs.getString(1);
		datos [1]=rs.getString(2);
                datos [2]=rs.getString(3);
                datos [3]=rs.getString(4);
                datos [4]=rs.getString(5);
                datos [5]=rs.getString(6);
                datos [6]=rs.getString(7);
                datos [7]=rs.getString(8);
                datos [8]=rs.getString(9);
                datos [9]=rs.getString(10);
                datos [10]=rs.getString(11);
                datos [11]=rs.getString(12);
                datos [12]=rs.getString(13);
                datos [13]=rs.getString(14);
                datos [14]=rs.getString(15);
                datos [15]=rs.getString(16);
                datos [16]=rs.getString(17);
                datos [17]=rs.getString(18);
                datos [18]=rs.getString(19);
                datos [19]=rs.getString(20);
                datos [20]=rs.getString(21);

                modelo.addRow(datos);
		}
		tabla.setModel(modelo);
		
	}catch (SQLException ex){
		Logger.getLogger(creacionempleado.class.getName()).log(Level.SEVERE, null, ex);
	
	}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoEstado = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        DateFecha = new com.toedter.calendar.JDateChooser();
        txtapellido = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtdireccion = new javax.swing.JTextField();
        combomun = new javax.swing.JComboBox();
        combodpto = new javax.swing.JComboBox();
        comboafp = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        comboempresa = new javax.swing.JComboBox();
        combonivel = new javax.swing.JComboBox();
        DateIngreso = new com.toedter.calendar.JDateChooser();
        combocargo = new javax.swing.JComboBox();
        combocivil = new javax.swing.JComboBox();
        btnGuardar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        txtnombre = new javax.swing.JTextField();
        txtdui = new javax.swing.JFormattedTextField();
        txttelefono = new javax.swing.JFormattedTextField();
        txtcorreo = new javax.swing.JTextField();
        txtnit = new javax.swing.JFormattedTextField();
        txtisss = new javax.swing.JFormattedTextField();
        txtnup = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        ButtonActivo = new javax.swing.JRadioButton();
        ButtonInactivo = new javax.swing.JRadioButton();
        txtsueldo = new javax.swing.JTextField();
        lblfecha = new javax.swing.JLabel();
        lblfechaing = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Creación de Empleado");
        setBackground(new java.awt.Color(252, 251, 251));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Creación de Empleado");

        jLabel2.setText("Id");

        jLabel3.setText("Nombre");

        jLabel4.setText("Estado Civil");

        jLabel5.setText("Fecha de nacimiento");

        jLabel6.setText("Teléfono");

        txtcodigo.setEditable(false);
        txtcodigo.setEnabled(false);

        DateFecha.setDateFormatString("yyyy-MM-dd");

        txtapellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtapellidoKeyTyped(evt);
            }
        });

        jLabel7.setText("Apellido");

        jLabel8.setText("Correo electronico");

        jLabel9.setText("Dirección");

        jLabel10.setText("Municipio");

        jLabel11.setText("Departamento");

        jLabel12.setText("DUI");

        jLabel13.setText("NIT");

        jLabel14.setText("ISSS");

        jLabel15.setText("AFP");

        jLabel16.setText("NUP");

        combomun.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Soyapango", "San Salvador", "Ilopango", "Apopa" }));
        combomun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combomunActionPerformed(evt);
            }
        });

        combodpto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "San Salvador", "Morazán", "La Unión ", "La Libertad", "San Miguel", "Santa Ana" }));

        comboafp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Crecer", "Confia", "IPSFA" }));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Datos personales");

        jLabel18.setText("Fecha de ingreso");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("Datos Laborales");

        jLabel20.setText("Empresa");

        jLabel21.setText("Nivel");

        jLabel22.setText("Cargo");

        jLabel23.setText("Sueldo");

        comboempresa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Item 2", "Item 3", "Item 4" }));

        combonivel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Nivel 1", "Nivel 2", "Nivel 3", "Nivel 4", "Nivel 5" }));

        DateIngreso.setDateFormatString("yyyy-MM-dd");
        DateIngreso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DateIngresoKeyTyped(evt);
            }
        });

        combocargo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Subgerente", "Gerente", "Agente " }));

        combocivil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Soltero/a", "Casado/a", "Divorciado/a", "Viudo/a" }));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jButton2.setText("Modificar");

        tabla.setAutoCreateRowSorter(true);
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        jButton3.setText("Buscar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });
        txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreKeyTyped(evt);
            }
        });

        try {
            txtdui.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtdui.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtduiKeyTyped(evt);
            }
        });

        try {
            txttelefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtnit.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-######-###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtnit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnitKeyTyped(evt);
            }
        });

        try {
            txtisss.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtisss.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtisssKeyTyped(evt);
            }
        });

        try {
            txtnup.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("############")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Estado"));

        GrupoEstado.add(ButtonActivo);
        ButtonActivo.setSelected(true);
        ButtonActivo.setText("Activo");
        ButtonActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActivoActionPerformed(evt);
            }
        });

        GrupoEstado.add(ButtonInactivo);
        ButtonInactivo.setText("Inactivo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonInactivo)
                    .addComponent(ButtonActivo))
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(ButtonActivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonInactivo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtsueldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsueldoActionPerformed(evt);
            }
        });
        txtsueldo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtsueldoKeyTyped(evt);
            }
        });

        lblfecha.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        lblfecha.setForeground(new java.awt.Color(240, 240, 240));
        lblfecha.setEnabled(false);

        lblfechaing.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        lblfechaing.setForeground(new java.awt.Color(240, 240, 240));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel5)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtcodigo)
                    .addComponent(DateFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(txtapellido)
                    .addComponent(txtdireccion)
                    .addComponent(combomun, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(combodpto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboafp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(combocivil, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtnombre)
                    .addComponent(txtdui)
                    .addComponent(txttelefono)
                    .addComponent(txtcorreo)
                    .addComponent(txtnit)
                    .addComponent(txtisss)
                    .addComponent(txtnup))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblfecha)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel21)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel20))
                                    .addComponent(jLabel22))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboempresa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(DateIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(combonivel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(combocargo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtsueldo))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblfechaing)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGuardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(260, 260, 260)))
                        .addGap(0, 89, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(16, 16, 16)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(combocivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(combomun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(combodpto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(txtdui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(txtnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(txtisss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(comboafp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(DateFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DateIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(lblfechaing))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboempresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(combonivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(combocargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(txtsueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(txtnup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonActivoActionPerformed
      ButtonActivo.setSelected(true);
    }//GEN-LAST:event_ButtonActivoActionPerformed

    
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

{Connection miConexion=(Connection) cConexion.GetConnection(); 
	try
	{ if (txtnombre.getText().equals(""))
{
	JOptionPane.showMessageDialog(null, "Ingrese nombre");
} else if (txtapellido.getText().equals(""))
{
	JOptionPane.showMessageDialog(null, "Ingrese apellido");
    
 } else if (combocivil.getSelectedItem().equals("Seleccionar"))
{
	JOptionPane.showMessageDialog(null, "Favor seleccione un estado civil");
}else if (DateFecha.getDate()==null)
{
	JOptionPane.showMessageDialog(null,"Favor ingresar fecha de nacimiento");
}else if (txttelefono.getText().equals(""))
{
	JOptionPane.showMessageDialog(null, "Ingrese numero de telefono");
}else if (txtcorreo.getText().equals(""))
{
	JOptionPane.showMessageDialog(null, "Ingrese dirección de correo");
}else if (txtdireccion.getText().equals(""))
{
	JOptionPane.showMessageDialog(null, "Ingrese dirección");
}else if (combomun.getSelectedItem().equals("Seleccionar"))
{
	JOptionPane.showMessageDialog(null, "Favor seleccione municipio");
}else if (combodpto.getSelectedItem().equals("Seleccionar"))
{
	JOptionPane.showMessageDialog(null, "Favor seleccione Departamento");
}else if (txtdui.getText().equals(""))
{
	JOptionPane.showMessageDialog(null, "Ingrese número de DUI");
}else if (txtnit.getText().equals(""))
{
	JOptionPane.showMessageDialog(null, "Ingrese número de NIT");
}else if (txtisss.getText().equals(""))
{
	JOptionPane.showMessageDialog(null, "Ingrese número de ISSS");
}else if (comboafp.getSelectedItem().equals("Seleccionar"))
{
	JOptionPane.showMessageDialog(null, "Favor seleccione AFP");
}else if (txtnup.getText().equals(""))
{
	JOptionPane.showMessageDialog(null, "Ingrese número de NUP");
}else if (DateIngreso.getDate()==null)
{
	JOptionPane.showMessageDialog(null,"Favor ingresar fecha de ingreso");
}else if (comboempresa.getSelectedItem().equals("Seleccionar"))
{
	JOptionPane.showMessageDialog(null, "Favor seleccione Empresa");
}else if (combonivel.getSelectedItem().equals("Seleccionar"))
{
	JOptionPane.showMessageDialog(null, "Favor seleccione Nivel");
}else if (combocargo.getSelectedItem().equals("Seleccionar"))
{
	JOptionPane.showMessageDialog(null, "Favor seleccione Cargo");
}else if (txtsueldo.getText().equals(""))
{
	JOptionPane.showMessageDialog(null, "Ingrese el sueldo");
}else {
    
    String formato = "yyyy/MM/dd";
       Date date = DateFecha.getDate();
       SimpleDateFormat sdf = new SimpleDateFormat (formato);
      lblfecha.setText(sdf.format(date));
    
      String formato1 = "yyyy/MM/dd";
       Date date1 = DateIngreso.getDate();
       SimpleDateFormat sdf1 = new SimpleDateFormat (formato1);
      lblfechaing.setText(sdf1.format(date1));
      
		PreparedStatement pst = miConexion.prepareStatement("insert into empleado (nombre, apellido, estado_civil, fechanacimiento, telefono, correo, direccion, municipio, departamento, dui, nit, isss, afp, nup, fechaingreso, empresa, nivel, cargo, sueldo) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
		
		JOptionPane.showMessageDialog(this, "Datos ingresados correctamente");
	 pst.setString(1, txtnombre.getText());
	 pst.setString(2, txtapellido.getText());
	 pst.setString(3, combocivil.getSelectedItem().toString());
         pst.setString(4, lblfecha.getText());
         pst.setString(5, txttelefono.getText());
	 pst.setString(6, txtcorreo.getText());
	 pst.setString(7, txtdireccion.getText());
	 pst.setString(8, combomun.getSelectedItem().toString());
	 pst.setString(9, combodpto.getSelectedItem().toString());
	 pst.setString(10, txtdui.getText());
	 pst.setString(11, txtnit.getText());
	 pst.setString(12, txtisss.getText());
	 pst.setString(13, comboafp.getSelectedItem().toString());
	 pst.setString(14, txtnup.getText());
         pst.setString(15, lblfechaing.getText());
	 pst.setString(16, comboempresa.getSelectedItem().toString());
	 pst.setString(17, combonivel.getSelectedItem().toString());
	 pst.setString(18, combocargo.getSelectedItem().toString());
	 pst.setString(19, txtsueldo.getText());

	 pst.executeUpdate();
         mostrardatos();
        }}
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Error "+ex.getMessage());
        }
}
    }//GEN-LAST:event_btnGuardarActionPerformed

    
    private void txtnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyTyped
      char c = evt.getKeyChar();
if ((c<'a' || c>'z') && (c<'A' || c>'Z')&& (c<' ' || c>' ')) evt.consume();
    }//GEN-LAST:event_txtnombreKeyTyped

    private void txtapellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellidoKeyTyped
 char c = evt.getKeyChar();
if ((c<'a' || c>'z') && (c<'A' || c>'Z')&& (c<' ' || c>' ')) evt.consume();
    }//GEN-LAST:event_txtapellidoKeyTyped

    private void txtduiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtduiKeyTyped
         char c = evt.getKeyChar();
if ((c<'0' || c>'9')) evt.consume();
    }//GEN-LAST:event_txtduiKeyTyped

    private void txtnitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnitKeyTyped
        char c = evt.getKeyChar();
if ((c<'0' || c>'9')) evt.consume();
    }//GEN-LAST:event_txtnitKeyTyped

    private void txtisssKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtisssKeyTyped
  char c = evt.getKeyChar();
if ((c<'0' || c>'9')) evt.consume();
    }//GEN-LAST:event_txtisssKeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
busqueda bus= new busqueda ();
bus.setLocationRelativeTo(null);
bus.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    private void txtsueldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsueldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsueldoActionPerformed

    private void txtsueldoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsueldoKeyTyped
        if(txtsueldo.getText().length()>=6) evt.consume();

        char tecla;
        tecla=evt.getKeyChar();
        String cod= txtsueldo.getText();
        int punto = cod.indexOf(".")+1;

        if(punto==0){
            if(!Character.isDigit(tecla)&&tecla!= KeyEvent.VK_BACK_SPACE&&tecla!=KeyEvent.VK_PERIOD){
                evt.consume();
                getToolkit().beep();
            }
        }else{
            if(!Character.isDigit(tecla)&&tecla!=KeyEvent.VK_BACK_SPACE){
                evt.consume();
                getToolkit().beep();
                }
            }
    }//GEN-LAST:event_txtsueldoKeyTyped

    private void DateIngresoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DateIngresoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_DateIngresoKeyTyped

    private void combomunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combomunActionPerformed
     
    }//GEN-LAST:event_combomunActionPerformed
                               
   

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    
    
    {
        
        
        
       
        java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
            public void run() {
                            setDefaultLookAndFeelDecorated(true);
                        SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.GreenMagicSkin");
                        SubstanceLookAndFeel.setCurrentTheme("org.jvnet.substance.theme.SubstanceAquaTheme");
                new creacionempleado().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ButtonActivo;
    private javax.swing.JRadioButton ButtonInactivo;
    private com.toedter.calendar.JDateChooser DateFecha;
    private com.toedter.calendar.JDateChooser DateIngreso;
    private javax.swing.ButtonGroup GrupoEstado;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox comboafp;
    private javax.swing.JComboBox combocargo;
    private javax.swing.JComboBox combocivil;
    private javax.swing.JComboBox combodpto;
    private javax.swing.JComboBox comboempresa;
    private javax.swing.JComboBox combomun;
    private javax.swing.JComboBox combonivel;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblfecha;
    private javax.swing.JLabel lblfechaing;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JFormattedTextField txtdui;
    private javax.swing.JFormattedTextField txtisss;
    private javax.swing.JFormattedTextField txtnit;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JFormattedTextField txtnup;
    private javax.swing.JTextField txtsueldo;
    private javax.swing.JFormattedTextField txttelefono;
    // End of variables declaration//GEN-END:variables
Connection miConexion= (Connection) cConexion.GetConnection();

}
